version: "3.8"
services:

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    networks:
        - clickhouse
    ulimits:
        nofile:
          soft: 262144
          hard: 262144 
    ports:
      - "8123:8123"
    volumes:
      - ./ddl/ddl-init.sql:/docker-entrypoint-initdb.d/ddl-init.sql
      - ./dml/dml-init.sql:/docker-entrypoint-initdb.d/dml-init.sql

volumes:
  clickhouse-data:
networks:
    clickhouse: